### PR TITLE
Site Revision

### PR DESCRIPTION
**Pull request by 0x22fe**

### CODE REVIEW

**Comment by plumer** [comment]
1. Looks like that the "team" page layouts all members by columns. Can we layout by rows as before?
2. Sort all faculty members and current students alphabetically by last name. (Dr. Benes is last which should actually be 2nd).
3. The border color for each "card" in teams page looks good. Can we use that onto "publications" page as well?
4. Set some vertical space below the navigation bar. Currently the vertical space between navbar and the main body is too thin.

**Comment by plumer** [comment]
5. Extend the navigation bar and footer background horizontally to both ends (but not the text content).

**Comment by 0x22fe** [comment]
Completed items 2, 4, and 5

**Comment by 0x22fe** [comment]
Completed items 1 and 3

**Pull request merged**
